# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: srlTest@0
  name: LRCloud
  inputs:
    serverEndpoint: 'LRC connection'
    tenantid: '159221713'
    projectid: '1'
    testid: '3973'

- script: echo Run ID of the LRC run $(LRC.LRC_RUN_ID) 
  displayName: 'Catch the Run Id of the LRC run'